### ISSUE TITLE
Silver Surfer

### ISSUE THREAD

**Issue by Kristories** [devtical/nova-qrcode-field#14]
Ref :  #11 #12 #13 #15

**Comment by Kreshnik** [comment]
Pretty please fix this issue 😇

**Comment by Synchro** [comment]
Some further detail that might help. The QR renders to this, which is an empty tag. There are no JS errors logged:

    <detail-qrcode index="3" resource-name="products" resource-id="66118" resource="[object Object]" field="[object Object]"></detail-qrcode>

**Comment by Synchro** [comment]
Is there anything we can do to help get this fixed? Do you know what the problem is?

**Comment by Kristories** [comment]
Please use `v2.0.0` using  `composer require devtical/nova-qrcode-field`.

Thank you for being so patient. We try to do our best.
