### ISSUE TITLE
is it possible to support nova 4.0 ?

### ISSUE THREAD

**Issue by a3mad** [devtical/nova-qrcode-field#18]
I installed the package over nova 4.0 but the fields doesn't appear, is it possible to upgrade it to support nova 4.0 ?

**Comment by Kristories** [comment]
What version are you using? Make sure you are using the `^v2.0` version.

This is a screenshot using Laravel Nova 4

![](https://github.com/devtical/nova-qrcode-field/raw/master/art/cover.png)

**Comment by a3mad** [comment]
It is working, I just didn't notice how it works the first time
