### ISSUE TITLE
[feature] Possibility to add padding around the image

### ISSUE THREAD

**Issue by mark-nicepants** [devtical/nova-qrcode-field#19]
I had a lot of trouble scanning QR-codes when looking at Nova in dark mode. It appears that the contrast between the QR corners and the dark blue nova background is prohibiting certain scanners. To avoid this it would be nice to have a padding parameter that gives the rendered image a bit of white padding.

**Comment by Kristories** [comment]
Released [v2.0.1](https://github.com/devtical/nova-qrcode-field/releases/tag/v2.0.1). Thanks @mark-nicepants
